#!/bin/bash

if [ $1 == "-d" ]
then suff=$2
shift
shift
for arg in "$@"
do name=$arg
name1=${name##*.}
name2=${name%.*}
echo $name2$suff"."$name1
done
else
suff=$1
shift
for arg in "$@"
do name=$arg
name1=${name##*.}
name2=${name%.*}
mv $name $name2$suff"."$name1
done
fi


#!/bin/bash

suff=$1
if [ -z $3 ]
then
for file in `find . -type f -name $2`
do
name=$file
name1=${name##*.}
name2=${name%.*}
mv $name $name2$suff"."$name1
done
else
for file in `find $3 -type f -name $2`
do
name=$file
name1=${name##*.}
name2=${name%.*}
mv $name $name2$suff"."$name1
done
fi



#!/bin/bash

size=$1
if [ $# -ne 2 ]
then for file in ./*
do
filesize=$(stat -c%s "$file")
if [ $filesize -gt $size ]
then echo $file
fi
done
else
for file in $2/*
do
filesize=$(stat -c%s "$file")
if [ $filesize -gt $size ]
then echo $file
fi
done
fi
